Azure/Guest-Configuration-Extension

.gitignore, main/cmds.go, main/cmds_test.go, main/main.go
Correcting the agent path.
---
=> Fixing the agent path

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
=> Updating .github files

misc/manifest.xml
=> manifest version update

.travis.yml, Makefile, main/cmds_test.go, main/main.go
=> make test working

.travis.yml, Makefile, main/cmds_test.go, main/schema.go
Fixing issue #16 
Added golint, gofmt, and go vet to Makefile under Test. 
Travis build now succeeds.
---
=> Fixing Travis build issue with golint, go vet, and gofmt

Makefile
only run tests after running godep restore
---
=> fix dependencies for godep in Makefile

main/cmds.go, main/main.go
Addresses issue #33 - moves flag output to logging instead of stdout
Also catches some missed errors (unzipping errors)
Removes unnecessary logging as well 
---
=> remove unnecessary logging and catch missed errors

main/cmds.go, main/errorCodes.go, main/exec.go, main/main.go, misc/manifest.xml
Checks for agent health in the precheck for enable
Refactored some code
---
=> checking agent health in the enable precheck

main/cmds.go, main/cmds_test.go, main/errorCodes.go, main/exec.go, main/main.go, pkg/seqnum/seqnum.go, pkg/seqnum/seqnum_test.go
=> added some more unit tests and created some more telemetry events

main/cmds.go, main/exec.go
=> agent version telemetry and status messages updated

main/cmds.go
the disable now disables the agent
telemetry is now refactored
---
=> disable command

main/cmds_test.go, misc/manifest.xml
=> version updated

misc/manifest.xml
We are ready to deploy the latest DSC agent.
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/guest-configuration-extension/55)
=> Update to latest DSC agent

misc/manifest.xml
Updating the DSC Agent package and version
---
- [x ] I have read the [contribution guidelines](https://github.com/Azure/Guest-Configuration-Extension/blob/master/.github/CONTRIBUTING.md).
=> updating agent package

misc/manifest.xml
Updating to the latest DSC agent and raising the version to 0.12.
---
- ~[ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.~
- ~[ ] If applicable, the PR references the bug/issue that it fixes in the description.~
- ~[ ] New Unit tests were added for the changes made and Travis.CI is passing.~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/guest-configuration-extension/61)
=> Update agent and raise version to 0.12

misc/manifest.xml
=> Update agent and raise version to 0.14

misc/manifest.xml
Update agent and raise version to 0.15 for next deployment
---
- ~[ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.~
- ~[ ] If applicable, the PR references the bug/issue that it fixes in the description.~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/guest-configuration-extension/66)
=> Update agent and raise versionto 0.15

misc/manifest.xml
Update agent and raise version to 0.16 for a new deployment.
---
- ~[ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.~
- ~[ ] If applicable, the PR references the bug/issue that it fixes in the description.~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/guest-configuration-extension/67)
=> Update agent and raise version to 0.16

misc/manifest.xml
Updating agent and raising version to 1.0 for release deployment.
---
- ~[ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.~
- ~[ ] If applicable, the PR references the bug/issue that it fixes in the description.~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/guest-configuration-extension/68)
=> Update agent and raise version to 1.0

misc/manifest.xml
=> Update agent and raise version to 1.1

.travis.yml
=> Update go version from 1.7 to 1.11 in Travis CI config

misc/manifest.xml
=> Update agent and raise version to 1.2

misc/manifest.xml
=> Update manifest to version 1.2.1 (agent binary is already updated)

misc/manifest.xml
Updated the DSC engine package for the release of version 1.3.0 to fix certificate issues on RedHat and CentOS.
---
~~Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.~~
~~If applicable, the PR references the bug/issue that it fixes in the description.~~
~~New Unit tests were added for the changes made and Travis.CI is passing.~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/guest-configuration-extension/75)
=> Release 1.3.0

misc/manifest.xml
=> Update DSC engine package for release 1.4.0

misc/manifest.xml
=> Update DSC engine package for release 1.5.0

misc/manifest.xml
Updating DSC agent package with changes for inventory/Update scenario.
---
- [ x] The title of the PR is clear and informative.
- [x ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x ] If applicable, the PR references the bug/issue that it fixes in the description.
- [x ] New Unit tests were added for the changes made and Travis.CI is passing.
- [x ] If …
=> Updating dsc agent package to release for inventory

misc/manifest.xml
=> Update DSC engine package for release 1.6.0

misc/manifest.xml
=> Update DSC engine package for release 1.7.0

misc/manifest.xml
=> Update DSC engine package for release 1.8.0

misc/manifest.xml
=> Release 1.9.0

misc/manifest.xml
=> Update DSC engine package for release 1.10.0

misc/manifest.xml
=> Update DSC engine package for release 1.11.0

misc/manifest.xml
---
- [x ] I have read the [contribution guidelines](https://github.com/Azure/Guest-Configuration-Extension/blob/master/.github/CONTRIBUTING.md).
=> Release 1.13.0.0 - GuestConfig Agent fix for agent deadlock issue.

main/cmds.go, main/handlersettings.go, main/schema.go, main/utils.go
=>   Add assignment name and content hash to dsc.config file

misc/manifest.xml
=> Update DSC engine package for release 1.13.1

main/cmds.go, main/handlersettings.go, main/schema.go, main/utils.go
Reverts Azure/Guest-Configuration-Extension#87
=> Revert "  Add assignment name and content hash to dsc.config file"

misc/manifest.xml
=> Update extension version.

misc/manifest.xml
=> Fix upgrade scenario

misc/manifest.xml
=> Update DSC engine package for release 1.14.0

misc/manifest.xml
=> Update DSC engine package for release 1.15.0

misc/manifest.xml
=> Update DSC engine package for release 1.16.0

misc/manifest.xml
=> Update DSC engine package for release 1.17.0

misc/manifest.xml
=> Update DSC engine package for release 1.18.0

misc/manifest.xml
=> Update DSC engine package for release 1.23.0

misc/manifest.xml
=> Publish Version 1.24.0.0 : Add support for USNAT

misc/manifest.xml
=> Publish Version 1.24.1 : Fix USNAT service endpoint name

misc/manifest.xml
=> Publish Version 1.25.0.0 : Bug fixes

misc/manifest.xml
Removed Rest Server.
updated cpprest binary from 2.10.2 to 2.10.14
fixed cmdline parameter parsing issue in gc_worker process
=> Publish Version 1.25.1 : Fix gc_worker cmdline parameter parsing issue

misc/manifest.xml
=> Publish Version 1.25.3 : Use new GAS service global endpoint for metadata call

misc/manifest.xml
=> Publish Version 1.25.4 : Fix private network scenario

misc/manifest.xml
=> Publish Version 1.25.5 : Revert server cert validation change

misc/manifest.xml
=> Publish Version 1.26.0 : Fix agent service restart hang

misc/manifest.xml
=> Publish Version 1.26.4 : gc_worker failing to load ssl library on CetOS/Redhat machines

misc/manifest.xml
=> Publish Version 1.26.5 : Support set/deployment with Custom policies and native resources

misc/manifest.xml
=> Publish Version 1.25.6 : Support latest linux distros

misc/manifest.xml
=> Publish Version 1.26.7 : Revert multiple assignment changes

misc/manifest.xml
Release notes:
1. Multiple assignment support (behind feature flag)
2. Latest linux distros (Redhat/CentOS8) support for Azure VMs.
3. Set Scenario Private Preview phase 1 (set support for native resource and custom policies)
4. Private networking (behind feature flag)
5. Powershell resource support on linux
=> Publish GuestConfiguration extension Version 1.26.8

misc/manifest.xml
Release Notes:-
1.	Added support for PowerShell policies on Linux.
2.	Bundle Powershell 7.2 with Linux package.
3.	Removing HEAD calls to reduce the COGS.
4.	Remove dependencies (endpoint mapping) from old Agent Service.
5.	Added support for Extension upgrade.
6.	Bug fix: support custom policies with Azure private network.
=> Publish GuestConfigurationForLinux Version 1.26.11

misc/manifest_to_deletexml
=> Delete Linux GCExtension version 0.2.0

misc/manifest_to_deletexml
=> Delete Linux GCExtension version 1.25.2

misc/manifest.xml
Publish Guest Configuration extension version 1.26.12
Release notes:-
1. Added support for PowerShell policies on Linux.
2. Bundle Powershell 7.2 with Linux package.
3. Removing HEAD calls to reduce the COGS.
4. Remove dependencies (endpoint mapping) from old Agent Service.
5. Added support for Extension upgrade.
6. Bug fix: support custom policies with Azure private network.
7. Improvements aroud Extension upgrade scenario.
=> Publish Guest Configuration extension version 1.26.12

misc/manifest_to_deletexml
=> Delete unused extension version 1.26.6 from prod regions

misc/manifest.xml
Publish Guest Configuration extension version 1.26.15
Release Notes:-
1.	Enable Multiple assignment feature
2.	Support "Audit before Set" scenario.
3.	Use powershell 7.1.2 on windows.
4.	Arc billing issue fix.
5.	Ext Bug Fix :- Get-JsonContent extension cmdlet is returning object instead of array of object. It started happening after gcagent migrated to ps7. The main issue is that ConvertFrom-Json cmdlet is not returning array when there is only one element in json array.
Added a workaround so that extension script will check the Get-JsonContent cmdlet return type first before using it.
=> Publish Guest Configuration extension version 1.26.15

misc/manifest.xml
Publish Guest Configuration extension version 1.26.18
Release Notes:-
1.      Remove private preview feature flag to enable set functionality for custom policy.
2.      Add feature flag to disable set functionality for custom policy.
=> Publish Guest Configuration extension version 1.26.18

misc/manifest.xml
Linux Version 1.26.29
Changes include:
1. Support showing callstack with coredump
2. Fix GuestConfiguration module performance issue
3. Read proxy information from file.
4. Enable notification listener for Arc.
5. Disable proxy settings if not being used explicitly by the customer.
6. Publish assignment out of proc.
7. Fix memory leak and crashes.
8. Do not read configmode from package metaconfig file.
=> Publish Guest Configuration extension version 1.26.29

misc/manifest.xml
=> Updating version to 1.26.30

misc/manifest.xml
Publish Guest Configuration extension version 1.26.34
=> Publish Guest Configuration extension version 1.26.34

misc/manifest.xml
Publish Guest Configuration extension version 1.26.36
Release notes:-
1. Enable support user assigned identity.
=> Publish Extension version 1.26.36

misc/manifest.xml
- [ x] The title of the PR is clear and informative.
- [ x] If needed, Version of the Extension was bumped in the misc/manifest.xml file.
=> Publish Extension Version 1.26.38

misc/manifest.xml
Full PowerShell cmdlet execution support
Support standard data type in policy parameters
Trim report if it is bigger than 100kb. 
Reliability fixes around service restart and policy report.
=> Publish Extension version 1.26.39

misc/manifest.xml
Release notes:
1. Support ApplyOnce assignment type
2. Sequential execution of the assignment
3. Get assignments call should get the priority and should execute every 5 minutes.
4. Disable service restart.
=> Publish Extension version 1.26.45

misc/manifest.xml
=> Publish Extension version 1.26.54

misc/manifest.xml
=> Publish Extension version 1.26.55

misc/manifest.xml
=> Publish Extension version 1.26.57

misc/manifest.xml
=> Publish Extension version 1.26.58

misc/manifest.xml
=> Publish Extension version 1.26.60

misc/manifest.xml
This change updates the agent to version 1.26.62.
* Now deletes the `System.Data.Sql.dll` file as the Guest Configuration Extension does not need this file.
---
=> Updates agent to 1.26.62 - removes SQL.dll after installing powershell

misc/manifest.xml
This change updates the agent to version 1.26.63.
* Now deletes the `System.Data.Sql.dll` file as the Guest Configuration Extension does not need this file, as the previous version #158 introduced a regression
---
---
=> Updates agent to 1.26.63 - removes SQL.dll after installing powershell

misc/manifest.xml
* Includes previous removal of PowerShell SQL dll file
* Includes linux specific bug fixes related to crashing on startup
---
```File list
C:\git\Guest-Configuration-Extension\agent>tree /F
Folder PATH listing
Volume serial number is A672-3809
C:.
│   GC_1.0.0.zip
│
├───GC_1.0.0
│   └───GC
│       │   agent_version.json
│       │   createdump
│       │   disable.sh
│       │   download_powershell_package.sh
│       │   em_extension_cleanup
│       │   enable.sh
│       │   extensioncleanup.sh
│       │   gc_linux_service
│       │   gc_worker
│       │   install.sh <--- confirmed
```
=> Includes new version, updating to 1.26.64

misc/manifest.xml
preparing release. This release contains changes these changes
removing cpprestsdk
adding boost beast.
updating boost from 1.66 to 1.80
=> preparing release 1.26.68.0

misc/manifest.xml
=> preparing release 1.26.71.0

misc/manifest.xml
=> updating linux version to 1.26.72

misc/manifest.xml
=> Preparing release 1.26.74

README.md
The current deploy command example in the README with version `0.8.0` fails with `ArtifactVersionNotFound`. This PR removes the `--version` argument to use the latest version by default.
---
=> docs(README.md): Remove version in deployment command

misc/manifest.xml
Reading in a new field for assignments "contentManagedIdentity" which is a user assigned managed identity that is used to download the package from the storage account without the use of a sas token url.
---
=> Adding changes to download file using user assigned managed identity

misc/manifest.xml
=> Updated the OpenSSL version

misc/manifest.xml
=> preparing release 1.26.79

misc/manifest.xml
Upgrading Openssl version to 3.4.0
---
=> preparing release 1.26.80

misc/manifest.xml
---
Version Update:
OpenSSL Update: Upgraded from version 3.4.0 to 3.4.1.
New Features:
Azure Linux 3 Support: Added support for Azure Linux 3.
Bug Fixes:
Deadlock Resolution: Resolved an issue causing a deadlock during policy execution.
Race Condition Fix: Addressed a race condition that was causing policy compliance to fluctuate, which was blocking remediation for both apply and monitor phases.
=> Release for 1.26.83

misc/manifest.xml
Version Update:
OpenSSL Update: Upgraded from version 3.4.0 to 3.4.1.
New Features:
Azure Linux 3 Support: Added support for Azure Linux 3.
Bug Fixes:
Deadlock Resolution: Resolved an issue causing a deadlock during policy execution.
---
=> release for 1.26.85

misc/manifest.xml
	Update to latest PowerShell version 7.4.7
	Update to .NET 8.0
---
=> release for 1.26.87

Godeps/Godeps.json, main/cmds_test.go, main/logger.go, main/main.go, misc/manifest.xml
Removing dependency on go-kit which has known security issues and using logrus library instead. We were only using go-kit for logging and the logging sublib of go-kit doesn't have any known vulnerabilities, but by using go-kit in our code at all, it imports those dependencies.
FIxes:
<a target="_blank" href="https://dev.azure.com/msazure/One/_componentGovernance/166084/alert/12361759?branchMoniker=master"> CVE-2024-45337</a>
<a target="_blank" href="https://dev.azure.com/msazure/One/_componentGovernance/166084/alert/10156120?branchMoniker=master"> CVE-2022-41723</a>
<a target="_blank" href="https://dev.azure.com/msazure/One/_componentGovernance/166084/alert/10156112?branchMoniker=master"> CVE-2023-47090</a>
<a target="_blank" href="https://dev.azure.com/msazure/One/_componentGovernance/166 …
=> Updating Log Library

Godeps/Godeps.json, main/logger.go, misc/manifest.xml
Removing dependency on Logrus which has a security vulnerability that is getting flagged.
Fixes:
https://dev.azure.com/msazure/One/_componentGovernance/Mgmt-GuestConfig-LinuxExtension/alert/10155856?typeId=32574209
---
=> Removing Dependency on Logrus

misc/manifest.xml
System Assigned Identity to download custom policy package.
Update to boost 1.83
---
=> Release for 1.29.92.0
